package server

const (
	templateLayout               = "layout.html"
	templateNotFound             = "404.html"
	templateInternalError        = "500.html"
	templateAccount              = "account.html"
	templateBreadcrumb           = "breadcrumb.html"
	templateFlash                = "flash.html"
	templateChangeEmail          = "change_email.html"
	templateChangePassword       = "change_password.html"
	templateConfirmEmail         = "confirm_email.html"
	templateConfirmEmailChange   = "confirm_email_change.html"
	templateForgotPassword       = "forgot_password.html"
	templateHome                 = "home.html"
	templateLogin                = "login.html"
	templateResetPassword        = "reset_password.html"
	templateRegister             = "register.html"
	templateResendVerification   = "resend_verification.html"
	templateVerifyEmail          = "verify_email.html"
	templateDeleteAccount        = "delete_account.html"
	templateTwoFactor            = "two_factor.html"
	templateTwoFactorBackupCodes = "two_factor_backup_codes.html"
	templateTwoFactorChallenge   = "two_factor_challenge.html"
	templatePasskeys             = "passkeys.html"
)
